// src/pages/Task8.js
import React, { useState, useCallback } from "react";
import styled, { useTheme } from "styled-components";
import { motion } from "framer-motion";
import Slider from "../components/Slider";
import ImageTransformViewer from "../components/ImageTransformViewer";
import { concaveMirrorPixelTransform } from "../utils/physics";

// --- Styled Components (Consistent with other tasks) ---
const TaskContainer = styled(motion.div)``;
const Title = styled.h2`
	margin-bottom: 1.5rem;
	font-weight: 700;
	color: ${({ theme }) => theme.text};
	border-left: 4px solid ${({ theme }) => theme.primary};
	padding-left: 1rem;
`;
const TwoColumnLayout = styled.div`
	display: grid;
	grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
	gap: 2rem;
	align-items: stretch;
`;
const ControlAndVizContainer = styled.div`
	background: ${({ theme }) => theme.accent};
	border: 1px solid ${({ theme }) => theme.line};
	border-radius: 12px;
	padding: 2rem;
	box-shadow: 0 4px 12px ${({ theme }) => theme.shadow};
	min-height: 500px;
	display: flex;
	flex-direction: column;
`;
const SummaryContainer = styled.div`
	grid-column: 1 / -1;
	background: ${({ theme }) => theme.accent};
	border-radius: 8px;
	padding: 1.5rem;
	line-height: 1.7;
	border: 1px solid ${({ theme }) => theme.line};
	margin-top: 2rem;
	font-size: 1rem;
`;
const SummaryTitle = styled.h3`
	margin-bottom: 1rem;
	color: ${({ theme }) => theme.primary};
`;
const Equation = styled.div`
	margin: 1rem 0;
	padding: 1rem;
	background: ${({ theme }) => theme.body};
	border-radius: 6px;
	text-align: center;
	font-family: "Courier New", Courier, monospace;
	font-size: 1.1rem;
`;

const Task8 = () => {
	const theme = useTheme();
	const [objectX, setObjectX] = useState(0.3);
	const [objectY, setObjectY] = useState(-0.4);
	const [objectWidth, setObjectWidth] = useState(0.2);
	const [mirrorRadius, setMirrorRadius] = useState(1.35);

	const mirrorTransform = useCallback(
		(point) => {
			return concaveMirrorPixelTransform(point, mirrorRadius);
		},
		[mirrorRadius],
	);

	const concaveMirror = {
		draw: (ctx, scale, originX, originY) => {
			ctx.strokeStyle = theme.primary;
			ctx.lineWidth = 4;
			ctx.beginPath();
			// Draw a concave arc centered at the origin, opening to the right
			ctx.arc(
				originX,
				originY,
				mirrorRadius * scale,
				-Math.PI / 2.5,
				Math.PI / 2.5,
			);
			ctx.stroke();
		},
	};

	return (
		<TaskContainer>
			<Title>Task 8: Real Image from a Concave Spherical Mirror</Title>
			<TwoColumnLayout>
				<ControlAndVizContainer>
					<h3 style={{ marginBottom: "1rem" }}>
						Mirror & Object Controls
					</h3>
					<Slider
						label="Mirror Radius (R)"
						min={0.5}
						max={2.0}
						step={0.05}
						value={mirrorRadius}
						onChange={(e) =>
							setMirrorRadius(parseFloat(e.target.value))
						}
						unit="m"
					/>
					<Slider
						label="Object X Position"
						min={0.1}
						max={0.9}
						step={0.01}
						value={objectX}
						onChange={(e) => setObjectX(parseFloat(e.target.value))}
						unit="m"
					/>
					<Slider
						label="Object Y Position"
						min={-0.8}
						max={0.8}
						step={0.01}
						value={objectY}
						onChange={(e) => setObjectY(parseFloat(e.target.value))}
						unit="m"
					/>
					<Slider
						label="Object Size"
						min={0.1}
						max={0.5}
						step={0.01}
						value={objectWidth}
						onChange={(e) =>
							setObjectWidth(parseFloat(e.target.value))
						}
					/>
				</ControlAndVizContainer>

				<ControlAndVizContainer style={{ padding: 0 }}>
					<ImageTransformViewer
						objectPosition={{ x: objectX, y: objectY }}
						objectSize={{ w: objectWidth, h: objectWidth }}
						transformation={mirrorTransform}
						mirror={concaveMirror}
					/>
				</ControlAndVizContainer>
			</TwoColumnLayout>
			<SummaryContainer>
				<SummaryTitle>
					Analysis: The "Floating Image" Experiment
				</SummaryTitle>
				<p>
					This simulation demonstrates the surprising formation of a{" "}
					<strong>real, inverted, and distorted image</strong> from a
					concave spherical mirror. The effect is produced by the
					convergence of two sets of rays: direct rays travelling from
					the object to the viewer, and rays that first reflect off
					the mirror's curved surface.
				</p>
				<Equation>
					Image (A, B) = Transform( Object (a,b), Radius R )
				</Equation>
				<p>
					The image is generated by applying the geometric
					transformation from the BPhO document to every pixel of the
					source image. Key characteristics are:
				</p>
				<ul>
					<li>
						<strong>Real:</strong> The image forms in front of the
						mirror where light rays physically converge.
					</li>
					<li>
						<strong>Inverted:</strong> The image is upside down.
					</li>
					<li>
						<strong>Highly Distorted:</strong> The mirror's
						curvature creates significant non-linear distortion
						(spherical aberration), which changes dynamically as the
						object moves.
					</li>
				</ul>
				<p>
					Use the sliders to move the object within the mirror's
					radius of curvature and observe the dramatic changes to the
					resulting real image.
				</p>
			</SummaryContainer>
		</TaskContainer>
	);
};

export default Task8;
